# Generated by Django 5.1.15 on 2026-05-11 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_images', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customimage',
            name='note',
            field=models.TextField(blank=True, help_text='관리자 메모. 라이브러리에서 검색 가능.'),
        ),
    ]
