# Generated by Django 5.1.15 on 2026-05-11 03:26

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0094_alter_page_locale'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('bio', models.TextField(blank=True)),
                ('website', models.URLField(blank=True)),
            ],
            options={
                'verbose_name': '작성자',
                'verbose_name_plural': '작성자',
            },
        ),
        migrations.CreateModel(
            name='BlogIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', models.CharField(blank=True, max_length=240)),
            ],
            options={
                'verbose_name': '블로그 목록',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='BlogPostPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('canonical_url', models.URLField(blank=True, help_text="Leave blank to use the page's URL.", max_length=255, verbose_name='Canonical URL')),
                ('intro', models.CharField(blank=True, help_text='목록·SEO description fallback', max_length=240)),
                ('body', wagtail.fields.StreamField([('heading', 3), ('paragraph', 4), ('image', 9), ('quote', 11), ('code', 13), ('embed', 14)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'max_length': 200, 'required': True}), 1: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('h2', 'H2'), ('h3', 'H3'), ('h4', 'H4')]}), 2: ('wagtail.blocks.CharBlock', (), {'help_text': '비워두면 자동 슬러그', 'max_length': 80, 'required': False}), 3: ('wagtail.blocks.StructBlock', [[('text', 0), ('level', 1), ('anchor', 2)]], {}), 4: ('apps.blog.blocks.content.ParagraphBlock', (), {}), 5: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': True}), 6: ('wagtail.blocks.CharBlock', (), {'max_length': 200, 'required': False}), 7: ('wagtail.blocks.CharBlock', (), {'help_text': '비워두면 이미지의 alt 사용', 'max_length': 200, 'required': False}), 8: ('wagtail.blocks.URLBlock', (), {'required': False}), 9: ('wagtail.blocks.StructBlock', [[('image', 5), ('caption', 6), ('alt_override', 7), ('link', 8)]], {}), 10: ('wagtail.blocks.TextBlock', (), {'required': True}), 11: ('wagtail.blocks.StructBlock', [[('text', 10), ('attribution', 6)]], {}), 12: ('wagtail.blocks.CharBlock', (), {'default': 'python', 'max_length': 30, 'required': False}), 13: ('wagtail.blocks.StructBlock', [[('language', 12), ('code', 10)]], {}), 14: ('wagtail.embeds.blocks.EmbedBlock', (), {'icon': 'media', 'label': '임베드 (YouTube/Vimeo/네이버TV…)', 'template': 'blog/blocks/embed.html'})})),
                ('seo_auto_generated_at', models.DateTimeField(blank=True, null=True)),
                ('seo_auto_locked', models.BooleanField(default=False, help_text='잠그면 Gemini 자동 메타 갱신이 이 페이지를 건너뜁니다.')),
            ],
            options={
                'verbose_name': '블로그 글',
                'ordering': ['-first_published_at'],
            },
            bases=('wagtailcore.page', models.Model),
        ),
        migrations.CreateModel(
            name='BlogPostTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('description', models.CharField(blank=True, max_length=240)),
            ],
            options={
                'verbose_name': '카테고리',
                'verbose_name_plural': '카테고리',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', models.CharField(blank=True, max_length=240)),
            ],
            options={
                'verbose_name': '홈',
            },
            bases=('wagtailcore.page',),
        ),
    ]
