# Generated by Django 5.1.15 on 2026-05-11 06:31

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_blogpostpage_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogindexpage',
            name='posts_per_page',
            field=models.IntegerField(default=10, help_text='페이지당 글 개수'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='body',
            field=wagtail.fields.StreamField([('hero', 5), ('category_feed', 12), ('category_grid', 17), ('category_showcase', 24), ('text', 25), ('image', 28), ('spacer', 30)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'max_length': 120, 'required': True}), 1: ('wagtail.blocks.CharBlock', (), {'max_length': 240, 'required': False}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': False}), 3: ('wagtail.blocks.CharBlock', (), {'max_length': 40, 'required': False}), 4: ('wagtail.blocks.CharBlock', (), {'help_text': '내부 경로 또는 외부 URL', 'max_length': 240, 'required': False}), 5: ('wagtail.blocks.StructBlock', [[('title', 0), ('subtitle', 1), ('image', 2), ('link_label', 3), ('link_url', 4)]], {}), 6: ('wagtail.blocks.CharBlock', (), {'max_length': 80, 'required': True}), 7: ('wagtail.blocks.CharBlock', (), {'max_length': 200, 'required': False}), 8: ('wagtail.snippets.blocks.SnippetChooserBlock', ('blog.Category',), {}), 9: ('wagtail.blocks.ListBlock', (8,), {'default': [], 'help_text': '비워두면 전체 카테고리', 'label': '포함할 카테고리'}), 10: ('wagtail.blocks.IntegerBlock', (), {'default': 4, 'help_text': '표시할 글 개수', 'max_value': 20, 'min_value': 1}), 11: ('wagtail.blocks.BooleanBlock', (), {'default': True, 'help_text': '첫 카테고리 페이지로 가는 ‘더 보기’ 링크', 'required': False}), 12: ('wagtail.blocks.StructBlock', [[('title', 6), ('subtitle', 7), ('categories', 9), ('count', 10), ('show_more_link', 11)]], {}), 13: ('wagtail.blocks.ListBlock', (8,), {'default': [], 'label': '포함할 카테고리'}), 14: ('wagtail.blocks.IntegerBlock', (), {'default': 4, 'max_value': 20, 'min_value': 1}), 15: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('2', '2열'), ('3', '3열')]}), 16: ('wagtail.blocks.BooleanBlock', (), {'default': True, 'required': False}), 17: ('wagtail.blocks.StructBlock', [[('title', 6), ('subtitle', 7), ('categories', 13), ('count', 14), ('columns', 15), ('show_more_link', 16)]], {}), 18: ('wagtail.blocks.CharBlock', (), {'default': '관심 분야', 'max_length': 80, 'required': True}), 19: ('wagtail.snippets.blocks.SnippetChooserBlock', ('blog.Category',), {'required': True}), 20: ('wagtail.blocks.IntegerBlock', (), {'default': 3, 'help_text': '카드 안에 미리 보일 글 개수', 'max_value': 10, 'min_value': 1}), 21: ('wagtail.blocks.CharBlock', (), {'help_text': '비워두면 카테고리 자체 description 사용', 'max_length': 240, 'required': False}), 22: ('wagtail.blocks.StructBlock', [[('category', 19), ('preview_count', 20), ('description_override', 21)]], {}), 23: ('wagtail.blocks.ListBlock', (22,), {'label': '카테고리 카드'}), 24: ('wagtail.blocks.StructBlock', [[('title', 18), ('items', 23), ('columns', 15)]], {}), 25: ('apps.blog.blocks.home.TextBlock', (), {}), 26: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': True}), 27: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('default', '기본'), ('wide', '넓게'), ('full', '전체 너비')]}), 28: ('wagtail.blocks.StructBlock', [[('image', 26), ('caption', 7), ('align', 27)]], {}), 29: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('20', 'Tiny'), ('30', 'X-Small'), ('40', 'Small'), ('50', 'Regular'), ('60', 'Large'), ('70', 'X-Large')]}), 30: ('wagtail.blocks.StructBlock', [[('height', 29)]], {})}, help_text='홈에 표시할 섹션들을 자유롭게 추가하세요. 히어로 / 글 리스트(라인) / 글 그리드(영상) / 카테고리 쇼케이스 / 자유 텍스트 / 큰 이미지 / 간격.'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='intro',
            field=models.CharField(blank=True, help_text='(선택) 페이지 상단 짧은 소개', max_length=240),
        ),
    ]
