# Generated by Django 5.1.15 on 2026-05-11 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_searchindexpage_tagindexpage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogindexpage',
            name='posts_per_page',
            field=models.IntegerField(default=5, help_text='페이지당 글 개수'),
        ),
    ]
