# Generated by Django 5.1.15 on 2026-05-11 08:21

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_blogindexpage_posts_per_page'),
        ('blog_images', '0002_customimage_note'),
        ('wagtailcore', '0094_alter_page_locale'),
    ]

    operations = [
        migrations.CreateModel(
            name='NavSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name_override', models.CharField(blank=True, help_text='(선택) 사이트 제목 덮어쓰기. 비워두면 WAGTAIL_SITE_NAME 사용', max_length=80)),
                ('tagline_override', models.CharField(blank=True, help_text='(선택) 푸터 태그라인 덮어쓰기', max_length=240)),
                ('header_menu', wagtail.fields.StreamField([('dropdown', 5), ('link', 7)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': '드롭다운 버튼 텍스트 (예: Blog)', 'max_length': 40, 'required': True}), 1: ('wagtail.blocks.CharBlock', (), {'max_length': 40, 'required': True}), 2: ('wagtail.blocks.CharBlock', (), {'help_text': '내부 경로(/blog/society/) 또는 외부 URL', 'max_length': 240, 'required': True}), 3: ('wagtail.blocks.StructBlock', [[('label', 1), ('url', 2)]], {}), 4: ('wagtail.blocks.ListBlock', (3,), {'label': '하위 메뉴'}), 5: ('wagtail.blocks.StructBlock', [[('label', 0), ('items', 4)]], {}), 6: ('wagtail.blocks.CharBlock', (), {'max_length': 240, 'required': True}), 7: ('wagtail.blocks.StructBlock', [[('label', 1), ('url', 6)]], {})}, help_text='헤더 메뉴 항목 (드롭다운/단일 링크)')),
                ('footer_menu', wagtail.fields.StreamField([('dropdown', 5), ('link', 7)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': '드롭다운 버튼 텍스트 (예: Blog)', 'max_length': 40, 'required': True}), 1: ('wagtail.blocks.CharBlock', (), {'max_length': 40, 'required': True}), 2: ('wagtail.blocks.CharBlock', (), {'help_text': '내부 경로(/blog/society/) 또는 외부 URL', 'max_length': 240, 'required': True}), 3: ('wagtail.blocks.StructBlock', [[('label', 1), ('url', 2)]], {}), 4: ('wagtail.blocks.ListBlock', (3,), {'label': '하위 메뉴'}), 5: ('wagtail.blocks.StructBlock', [[('label', 0), ('items', 4)]], {}), 6: ('wagtail.blocks.CharBlock', (), {'max_length': 240, 'required': True}), 7: ('wagtail.blocks.StructBlock', [[('label', 1), ('url', 6)]], {})}, help_text='푸터 메뉴 항목')),
                ('footer_extra', models.CharField(blank=True, help_text='푸터 하단 한 줄 (예: © 2026 …)', max_length=240)),
                ('default_og_image', models.ForeignKey(blank=True, help_text='글 없는 페이지에 공유될 기본 OG/소셜 썸네일', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='blog_images.customimage')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'verbose_name': '사이트 네비게이션',
            },
        ),
    ]
