# Generated by Django 5.1.15 on 2026-05-11 13:25

import apps.blog.models
import django.db.models.deletion
import wagtail.contrib.routable_page.models
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_category_options_category_order_and_more'),
        ('wagtailcore', '0094_alter_page_locale'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogindexpage',
            name='category_group',
            field=models.ForeignKey(blank=True, help_text='이 그룹의 자식 카테고리 글만 표시. 비워두면 모든 글.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='blog.category', verbose_name='카테고리 그룹 (부모)'),
        ),
        migrations.CreateModel(
            name='ProjectIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', models.CharField(blank=True, max_length=240)),
                ('intro_body', wagtail.fields.StreamField([('hero', 5), ('category_feed', 13), ('category_grid', 19), ('category_showcase', 26), ('text', 27), ('image', 30), ('spacer', 32)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'max_length': 120, 'required': True}), 1: ('wagtail.blocks.CharBlock', (), {'max_length': 240, 'required': False}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': False}), 3: ('wagtail.blocks.CharBlock', (), {'max_length': 40, 'required': False}), 4: ('wagtail.blocks.CharBlock', (), {'help_text': '내부 경로 또는 외부 URL', 'max_length': 240, 'required': False}), 5: ('wagtail.blocks.StructBlock', [[('title', 0), ('subtitle', 1), ('image', 2), ('link_label', 3), ('link_url', 4)]], {}), 6: ('wagtail.blocks.CharBlock', (), {'max_length': 80, 'required': True}), 7: ('wagtail.blocks.CharBlock', (), {'max_length': 200, 'required': False}), 8: ('wagtail.snippets.blocks.SnippetChooserBlock', ('blog.Category',), {}), 9: ('wagtail.blocks.ListBlock', (8,), {'default': [], 'help_text': '비워두면 전체 카테고리', 'label': '포함할 카테고리'}), 10: ('wagtail.blocks.IntegerBlock', (), {'default': 4, 'help_text': '페이지당 글 개수', 'max_value': 20, 'min_value': 1}), 11: ('wagtail.blocks.CharBlock', (), {'default': 'thoughts', 'help_text': '페이지 번호 URL 파라미터 키 (?thoughts=2). 페이지 내 다른 섹션과 겹치지 않게.', 'max_length': 30, 'required': True}), 12: ('wagtail.blocks.BooleanBlock', (), {'default': True, 'help_text': '첫 카테고리 페이지로 가는 ‘더 보기’ 링크', 'required': False}), 13: ('wagtail.blocks.StructBlock', [[('title', 6), ('subtitle', 7), ('categories', 9), ('count', 10), ('section_key', 11), ('show_more_link', 12)]], {}), 14: ('wagtail.blocks.ListBlock', (8,), {'default': [], 'label': '포함할 카테고리'}), 15: ('wagtail.blocks.IntegerBlock', (), {'default': 4, 'max_value': 20, 'min_value': 1}), 16: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('2', '2열'), ('3', '3열')]}), 17: ('wagtail.blocks.CharBlock', (), {'default': 'videos', 'help_text': '페이지 번호 URL 파라미터 키', 'max_length': 30, 'required': True}), 18: ('wagtail.blocks.BooleanBlock', (), {'default': True, 'required': False}), 19: ('wagtail.blocks.StructBlock', [[('title', 6), ('subtitle', 7), ('categories', 14), ('count', 15), ('columns', 16), ('section_key', 17), ('show_more_link', 18)]], {}), 20: ('wagtail.blocks.CharBlock', (), {'default': '관심 분야', 'max_length': 80, 'required': True}), 21: ('wagtail.snippets.blocks.SnippetChooserBlock', ('blog.Category',), {'required': True}), 22: ('wagtail.blocks.IntegerBlock', (), {'default': 3, 'help_text': '카드 안에 미리 보일 글 개수', 'max_value': 10, 'min_value': 1}), 23: ('wagtail.blocks.CharBlock', (), {'help_text': '비워두면 카테고리 자체 description 사용', 'max_length': 240, 'required': False}), 24: ('wagtail.blocks.StructBlock', [[('category', 21), ('preview_count', 22), ('description_override', 23)]], {}), 25: ('wagtail.blocks.ListBlock', (24,), {'label': '카테고리 카드'}), 26: ('wagtail.blocks.StructBlock', [[('title', 20), ('items', 25), ('columns', 16)]], {}), 27: ('apps.blog.blocks.home.TextBlock', (), {}), 28: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': True}), 29: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('default', '기본'), ('wide', '넓게'), ('full', '전체 너비')]}), 30: ('wagtail.blocks.StructBlock', [[('image', 28), ('caption', 7), ('align', 29)]], {}), 31: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('20', 'Tiny'), ('30', 'X-Small'), ('40', 'Small'), ('50', 'Regular'), ('60', 'Large'), ('70', 'X-Large')]}), 32: ('wagtail.blocks.StructBlock', [[('height', 31)]], {})}, help_text='프로젝트 페이지 상단 자유 편집 블록')),
                ('posts_per_page', models.IntegerField(default=10)),
                ('category_group', models.ForeignKey(blank=True, help_text="이 그룹의 자식 카테고리 글만 표시 (예: '프로젝트').", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='blog.category', verbose_name='카테고리 그룹 (부모)')),
            ],
            options={
                'verbose_name': '프로젝트 목록',
            },
            bases=(apps.blog.models._CategoryGroupIndexMixin, wagtail.contrib.routable_page.models.RoutablePageMixin, 'wagtailcore.page'),
        ),
    ]
