# Generated by Django 5.1.15 on 2026-05-11 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_blogindexpage_category_group_projectindexpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='navsettings',
            name='ga4_dashboard_url',
            field=models.URLField(blank=True, help_text='GA4 대시보드 URL (통계 페이지 ‘GA 열기’ 버튼에 사용). GA4 admin → 속성 → URL 복사.', max_length=500),
        ),
        migrations.AddField(
            model_name='navsettings',
            name='ga4_measurement_id',
            field=models.CharField(blank=True, help_text='Google Analytics 4 측정 ID (예: G-XXXXXXXXXX). 비워두면 GA 태그 미삽입.', max_length=20),
        ),
    ]
