# Generated by Django 5.1.15 on 2026-05-19 02:08

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_navsettings_ga'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpostpage',
            name='body',
            field=wagtail.fields.StreamField([('heading', 3), ('paragraph', 4), ('image', 9), ('quote', 11), ('code', 13), ('divider', 15), ('embed', 16), ('map', 23)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'max_length': 200, 'required': True}), 1: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('h2', 'H2'), ('h3', 'H3'), ('h4', 'H4')]}), 2: ('wagtail.blocks.CharBlock', (), {'help_text': '비워두면 자동 슬러그', 'max_length': 80, 'required': False}), 3: ('wagtail.blocks.StructBlock', [[('text', 0), ('level', 1), ('anchor', 2)]], {}), 4: ('apps.blog.blocks.content.ParagraphBlock', (), {}), 5: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': True}), 6: ('wagtail.blocks.CharBlock', (), {'max_length': 200, 'required': False}), 7: ('wagtail.blocks.CharBlock', (), {'help_text': '비워두면 이미지의 alt 사용', 'max_length': 200, 'required': False}), 8: ('wagtail.blocks.URLBlock', (), {'required': False}), 9: ('wagtail.blocks.StructBlock', [[('image', 5), ('caption', 6), ('alt_override', 7), ('link', 8)]], {}), 10: ('wagtail.blocks.TextBlock', (), {'required': True}), 11: ('wagtail.blocks.StructBlock', [[('text', 10), ('attribution', 6)]], {}), 12: ('wagtail.blocks.CharBlock', (), {'default': 'python', 'max_length': 30, 'required': False}), 13: ('wagtail.blocks.StructBlock', [[('language', 12), ('code', 10)]], {}), 14: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('line', '가는 선'), ('dots', '점 세 개'), ('space', '여백만 (선 없음)')], 'help_text': '구분선 모양'}), 15: ('wagtail.blocks.StructBlock', [[('style', 14)]], {}), 16: ('wagtail.embeds.blocks.EmbedBlock', (), {'icon': 'media', 'label': '임베드 (YouTube/Vimeo/네이버TV…)', 'template': 'blog/blocks/embed.html'}), 17: ('wagtail.blocks.CharBlock', (), {'help_text': '예: 서울 강남구 테헤란로 152', 'max_length': 200, 'required': True}), 18: ('wagtail.blocks.CharBlock', (), {'help_text': '지도 위 표시명 (장소 이름 등)', 'max_length': 80, 'required': False}), 19: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('naver', '네이버 지도'), ('google', '구글 지도')], 'help_text': '지도 제공자'}), 20: ('wagtail.blocks.IntegerBlock', (), {'default': 16, 'max_value': 20, 'min_value': 1}), 21: ('wagtail.blocks.IntegerBlock', (), {'default': 360, 'max_value': 720, 'min_value': 180}), 22: ('wagtail.blocks.BooleanBlock', (), {'default': True, 'help_text': '‘지도에서 열기’ 버튼 표시', 'required': False}), 23: ('wagtail.blocks.StructBlock', [[('address', 17), ('label', 18), ('provider', 19), ('zoom', 20), ('height', 21), ('show_link', 22)]], {})}),
        ),
    ]
