# Generated by Django 5.1.15 on 2026-05-11 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MigrationRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command', models.CharField(max_length=80)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('success', models.BooleanField(default=False)),
                ('counters', models.JSONField(default=dict)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='MigrationMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wp_id', models.IntegerField()),
                ('kind', models.CharField(choices=[('post', 'Post'), ('page', 'Page'), ('attachment', 'Attachment'), ('category', 'Category'), ('tag', 'Tag'), ('user', 'User')], max_length=20)),
                ('wagtail_pk', models.IntegerField(help_text='대응 Wagtail/Django 모델의 PK')),
                ('wagtail_model', models.CharField(help_text="예: 'blog.BlogPostPage', 'blog_images.CustomImage'", max_length=80)),
                ('extra', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['wagtail_model', 'wagtail_pk'], name='blog_migrat_wagtail_0095bd_idx')],
                'constraints': [models.UniqueConstraint(fields=('kind', 'wp_id'), name='uniq_wp_obj')],
            },
        ),
    ]
