# Generated by Django 5.1.15 on 2026-05-11 03:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0094_alter_page_locale'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitorIdentity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('nickname', models.CharField(max_length=20, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('ip_hash', models.CharField(db_index=True, max_length=64)),
                ('user_agent_hash', models.CharField(blank=True, max_length=64)),
                ('is_trusted', models.BooleanField(default=False, help_text='approved 댓글 N건 이상이면 자동 승격')),
                ('is_blocked', models.BooleanField(default=False)),
                ('notify_replies', models.BooleanField(default=False, help_text='답글 알림 옵트인')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
                ('nickname_changed_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BlockedIdentifier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('ip', 'IP'), ('email', 'Email'), ('nick', 'Nickname')], max_length=10)),
                ('value_hash', models.CharField(max_length=64)),
                ('reason', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('kind', 'value_hash'), name='uniq_blocked')],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname_snapshot', models.CharField(max_length=20)),
                ('body', models.TextField()),
                ('body_html', models.TextField()),
                ('ip_hash', models.CharField(max_length=64)),
                ('user_agent_hash', models.CharField(blank=True, max_length=64)),
                ('spam_score', models.FloatField(default=0.0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('spam', 'Spam'), ('deleted', 'Deleted')], default='approved', max_length=10)),
                ('moderation_reason', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admin_user', models.ForeignKey(blank=True, help_text='관리자가 작성한 답글', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_comments', to=settings.AUTH_USER_MODEL)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='wagtailcore.page')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='blog_comments.comment')),
                ('visitor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comments', to='blog_comments.visitoridentity')),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['page', 'status', 'created_at'], name='blog_commen_page_id_23a1fb_idx')],
                'constraints': [models.UniqueConstraint(fields=('page', 'ip_hash', 'body'), name='uniq_dup_comment')],
            },
        ),
    ]
