# Generated by Django 5.1.15 on 2026-05-11 07:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_comments', '0001_initial'),
        ('wagtailcore', '0094_alter_page_locale'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_hash', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='wagtailcore.page')),
                ('visitor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='likes', to='blog_comments.visitoridentity')),
            ],
            options={
                'indexes': [models.Index(fields=['page'], name='blog_commen_page_id_097ad5_idx')],
                'constraints': [models.UniqueConstraint(fields=('page', 'ip_hash'), name='uniq_like_per_ip_per_page')],
            },
        ),
    ]
