# Generated by Django 5.1.15 on 2026-05-11 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_comments', '0002_postlike'),
        ('wagtailcore', '0094_alter_page_locale'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_hash', models.CharField(max_length=64)),
                ('date', models.DateField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_views', to='wagtailcore.page')),
            ],
            options={
                'indexes': [models.Index(fields=['page', 'date'], name='blog_commen_page_id_891891_idx'), models.Index(fields=['date'], name='blog_commen_date_e3b04c_idx')],
                'constraints': [models.UniqueConstraint(fields=('page', 'ip_hash', 'date'), name='uniq_view_per_ip_per_day')],
            },
        ),
    ]
